### PR TITLE
Update to new API from Immich

### PR DESCRIPTION
**Pull request by Allram**
Update node_helper.js to accomodate the new API changes in Immich from v1.106+

this also fixed https://github.com/pelaxa/MMM-ImmichSlideShow/issues/14

### CODE REVIEW

**Comment by Snille** [comment]
Looks like it's working for me. :)
Thank you!

**Comment by etymotic** [comment]
Working for me.

**Comment by etymotic** [comment]
After a while I started getting `[ERROR] MMM-ImmichSlideShow :: node_helper :: Oops!  Exception while loading and converting image(2) timeout of 5000ms exceeded`. A restart of Magic Mirror resolved it. No idea if it's related to this change, but thought I'd mention it.

**Comment by pelaxa** [comment]
Thanks for the pull request and the quick turn around.

Can you resubmit and update the version to: 0.9.0 in package.json so folks will get notified of the update?

**Review by pelaxa — APPROVED** [review]

**Pull request merged**
